version: '3.9'

services:
  bot:
    image: ghcr.io/soulofsorrow/tempvoice:latest  # offizielles Image
    # build: .                                     # optional: lokal bauen
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "--eval", "console.log('ok')"]
      interval: 30s
      timeout: 10s
      retries: 3
