name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  verify-lockfile:
    name: 🔍 Check Lockfile Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install deps & check for lockfile changes
        run: |
          npm install --package-lock-only
          if ! git diff --exit-code package-lock.json; then
            echo "❌ Lockfile is out of sync with package.json"
            echo "🛠  Run 'npm install' and commit the updated package-lock.json"
            exit 1
          fi

  lint:
    needs: verify-lockfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run lint

  spellcheck:
    needs: verify-lockfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: check-spelling/check-spelling@main
        with:
          config: .github/spelling
